training_data_filepath: "/data/processed/training.pt"
test_data_filepath: "/data/processed/test.pt"
trained_model_filepath: "models/trained_model.pth"
training_figures_filepath: "reports/figures/"
training_statistics_filepath: "data/processed/"
mapping_filepath: "data/processed/mapping.json"